# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Latlongcalc
                                 A QGIS plugin
 Allows conversion of latitude and longitude degrees between decimal degrees and DMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-17
        copyright            : (C) 2021 by André ECO
        email                : andre.estevam97@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Latlongcalc class from file Latlongcalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .latlongcalc import Latlongcalc
    return Latlongcalc(iface)
